name: Build Docker Image Multi Account

on:
  push:
    branches:
      - main
  workflow_dispatch:   # 👈 ini yang bikin bisa run manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare accounts
        run: |
          echo "${{ secrets.DOCKER_ACCOUNTS }}" > accounts.txt

      - name: Build image once
        run: |
          docker build -t temp-image:latest .

      - name: Tag & Push to all accounts
        run: |
          > results.txt

          while IFS= read -r LINE
          do
            USERNAME=$(echo $LINE | cut -d: -f1)
            PASSWORD=$(echo $LINE | cut -d: -f2)

            REPO=$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c8)
            FULL="$USERNAME/$REPO:latest"

            echo "🚀 Pushing $FULL"

            echo $PASSWORD | docker login -u $USERNAME --password-stdin

            docker tag temp-image:latest $FULL
            docker push $FULL

            echo "https://hub.docker.com/r/$FULL" >> results.txt

            docker logout
            sleep 2

          done < accounts.txt

      - name: Show results
        run: |
          echo "==== RESULT LIST ===="
          cat results.txt

      - name: Upload result list
        uses: actions/upload-artifact@v4
        with:
          name: docker-repos
          path: results.txt
